const palette = {
  primary: '#0F766E',
  primaryDark: '#115E59',
  primarySoft: '#CCFBF1',
  accent: '#F97316',
  danger: '#DC2626',
  success: '#059669',
  warning: '#D97706',
  border: '#E5E7EB',
  muted: '#6B7280',
  card: '#FFFFFF',
  bg: '#F3F6F5',
  text: '#111827',
  textInverse: '#FFFFFF',
};

export default {
  light: {
    text: palette.text,
    textMuted: palette.muted,
    textInverse: palette.textInverse,
    background: palette.bg,
    card: palette.card,
    border: palette.border,
    tint: palette.primary,
    primary: palette.primary,
    primaryDark: palette.primaryDark,
    primarySoft: palette.primarySoft,
    accent: palette.accent,
    danger: palette.danger,
    success: palette.success,
    warning: palette.warning,
    tabIconDefault: '#9CA3AF',
    tabIconSelected: palette.primary,
  },
  dark: {
    text: '#F9FAFB',
    textMuted: '#9CA3AF',
    textInverse: '#FFFFFF',
    background: '#0B1220',
    card: '#111827',
    border: '#1F2937',
    tint: '#2DD4BF',
    primary: '#14B8A6',
    primaryDark: '#0F766E',
    primarySoft: '#134E4A',
    accent: '#FB923C',
    danger: '#F87171',
    success: '#34D399',
    warning: '#FBBF24',
    tabIconDefault: '#6B7280',
    tabIconSelected: '#2DD4BF',
  },
};
